repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: spotless
        name: Spotless code formatter
        description: Run spotless:apply task
        types: [ java ]
        entry: scripts/hooks/spotless-apply-pre-commit
        language: script
        require_serial: true
