spring:
  application:
    name: bookstore-webapp
  security:
    oauth2:
      client:
        registration:
          bookstore-webapp:
            client-id: bookstore-webapp
            client-secret: QaGwNlu50ybnoUd9Q8oQ5Y3ZOMUsoO4V
            authorization-grant-type: authorization_code
            scope: openid, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/bookstore-webapp"
        provider:
          bookstore-webapp:
            issuer-uri: ${bookstore.oauth2.realm-url}

server:
  port: 8080
  shutdown: graceful

bookstore:
  api-gateway-url: http://localhost:8989
  oauth2:
    server-url: http://localhost:9191
    realm-url: ${bookstore.oauth2.server-url}/realms/bookstore

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0
